version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            zip -r inventory.zip .
            cp inventory.zip ~/repo/artifacts
      - store_artifacts:
          path: ~/repo/artifacts

  build-cache:
    docker:
      - image: cimg/python:3.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            zip -r inventory.zip .
            cp inventory.zip ~/repo/artifacts
      - store_artifacts:
          path: ~/repo/artifacts
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  parallel-tests:
    docker:
      - image: cimg/python:3.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run Tests Parallely
          command: |
            python billing_system.py
            python test_billing_system_1.py
            python test_billing_system_2.py
    parallelism: 2

  sequential-tests:
    docker:
      - image: cimg/python:3.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Tests Sequentially
          command: |
            python billing_system.py
            python test_billing_system_1.py
            python test_billing_system_2py

workflows:
  version: 2
  build-on-push-1:
    jobs:
      - build
      - parallel-tests:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - parallel-tests
  
  build-on-push-2:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-cache
      - sequential-tests:
          requires:
            - build-cache
      - hold:
          type: approval
          requires:
            - build-cache
            - sequential-tests
